output errors to stderr instead of stdout

diff --git a/phpenv b/phpenv
--- a/phpenv
+++ b/phpenv
@@ -11,7 +11,7 @@ PHP="/usr/bin/php${PHP_VERSION}"
 
 # if PHP executable is not really executable, fail hard
 if ! [ -x "$(command -v ${PHP})" ]; then
-    echo "Error: PHP executable not found or not executable (${PHP})" >&2
+    echo >&2 "Error: PHP executable not found or not executable (${PHP})"
     exit 1;
 fi
 
diff --git a/phpenv-php-current-version b/phpenv-php-current-version
--- a/phpenv-php-current-version
+++ b/phpenv-php-current-version
@@ -5,7 +5,7 @@ if [ $# -ne 1 ]; then
     echo >&2 "usage: phpenv-php-current-version domain"
     exit 1;
 elif [[ "$1" =~ [^0-9a-zA-Z_-] ]]; then
-    echo "Domain may only contain alphanumerical characters (and the '_' and '-' characters)";
+    echo >&2 "Domain may only contain alphanumerical characters (and the '_' and '-' characters)"
     exit 1;
 fi
 DOMAIN=$1
@@ -17,7 +17,7 @@ unset IFS
 
 # make sure we detected exactly one FPM configuration file
 if ! [ ${#FPM_CONF[@]} -eq 1 ]; then
-    echo "Error: Failed to detect current PHP version"
+    echo >&2 "Error: Failed to detect current PHP version"
     exit 1;
 fi
 
